/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs");
const app = express();

app.use(bodyParser.json());
app.use(express.json());

let id = 0;

function readFile() {
  const str = fs.readFileSync("todos.json", "utf-8");
  const todos = JSON.parse(str);
  return todos;
}

function writeFile(todos) {
  const str = fs.writeFileSync("todos.json", JSON.stringify(todos, null, 2));
}

function assignId(req, res, next) {
  const todos = readFile();
  id = todos.length > 0 ? todos[todos.length - 1].id + 1 : id;
  next();
}

app.get("/", (req, res) => {
  res.send("Hello World");
});

app.post("/create/todo", assignId, (req, res) => {
  const title = req.body.title;
  const description = req.body.description;
  let todos = readFile();
  todos.push({ id: id, title: title, description: description });
  writeFile(todos);
  res.status(201).send(todos);
});

app.put("/todo", (req, res) => {
  const paramId = parseInt(req.query.id);
  if (isNaN(paramId)) {
    return res.status(404).json({ error: "Todo not found" });
  }
  let todos = readFile();
  let todo = todos.findIndex((each) => each.id === paramId);
  if (todo === -1) {
    res.status(404).json({ error: "Todo not found" });
  }
  todos[todo].title = req.body.title;
  todos[todo].description = req.body.description;
  writeFile(todos);
  res.json(todos);
});

app.get("/todos", (req, res) => {
  let todos = readFile();
  res.send(todos);
});

app.get("/todo", (req, res) => {
  const paramId = parseInt(req.query.id);
  if (isNaN(paramId)) {
    return res.status(404).json({ error: "Todo not found" });
  }
  let todos = readFile();
  const todoById = todos.find((each) => each.id === paramId);
  if (!todoById) {
    res.status(404).json({ error: "Todo not found" });
  } else {
    res.json(todoById);
  }
});

app.delete("/todo", (req, res) => {
  const paramId = parseInt(req.query.id);
  if (isNaN(paramId)) {
    return res.status(404).json({ error: "Todo not found" });
  }
  let todos = readFile();
  const todoExists = todos.find((each) => each.id === paramId);
  if (!todoExists) {
    return res.status(404).json({ error: "Todo not found" });
  }
  todos = todos.filter((each) => each.id !== paramId);
  writeFile(todos);
  res.status(200).send(todos);
});

app.use((req, res) => {
  res.status(404).json({ error: "Route not found" });
});

app.listen(3000, () => {
  console.log("Server is running on http://localhost:3000");
});

module.exports = app;